### ISSUE TITLE
search & replace on gitify export

### ISSUE THREAD

**Issue by tjventurini** [modmore/Gitify#212]
Just tried to make search & replace over all contents (_data/content) to change some paths that changed.

While in the manager everything is now right, in the frontend, there are still the old links.

The exact case: I moved all images, videos, and pdfs from `assets/{images,videos,pdf}` to `assets/uploads/{images,videos,pdf}`. To change this asap, I did a search and replace over all exported contents. Now in the manager, the paths are alright, but in the frontend there are still the old paths. This is related to cbFields and tvs as far as I can tell after a quick overview (we have easily 5000 sites so I just randomly checked some sites and thats the ones that pointed out).

I found the 
        truncate_on_force:
            - modTemplateVarResource

statement in the .gitify file, do I have to take care of some more stuff to make this easily?

I ofcorse cleared the cache, but so far, I could only fix this for some sites by saving them again (and there fore generate the new cached element), so I'm not shure what blocks this process :confused: 

Thank you :)

**Comment by hugopeek** [comment]
Did you figure this one out already @tjventurini?

You mention cbFields, meaning you're using ContentBlocks.. You probably have to do a search/replace on the content inside the Properties field too, otherwise ContentBlocks will revert your edits to the main Content field back how it was before.

The data in the Properties field is stored as JSON, so the syntax for a path will be slightly different. Something like:
```
{\"main\":[{\"url\":\"uploads\/img\/content\/2017\/some_image.svg\" ...
```
You'll have to run a second find/replace to address that.

As for the TV issue: I don't know what would cause that. Maybe that's something media source related?

**Comment by tjventurini** [comment]
Sry but I didn't remember how I solved it. But thank you for the support.
