### ISSUE TITLE
Gitify install of MODX result in no styling of manager

### ISSUE THREAD

**Issue by digitalpenguin** [modmore/Gitify#45]
Tried a couple of times. Gitify's install of MODX 2.3.2 results in manager without styling.
JS and CSS compression is off. Cleared cache dir to no avail. All perms 777.

**Comment by designbywilliam** [comment]
Interesting, i have had one similar experience. I used digital oceans lamp, and installed modx through Gitify. And i couldnt see anything , not even the log in window of the manager.

I then tried installing modx normally, and cloned gitify into it and just the init file , and that resulted in breaking the manager again. I gave up then and there because i was in a hurry. I thought of it as some other kind of issue and just reinstalled modx and went ahead as i normally would. But you raising this issue makes me wanna share my experience.

**Comment by Mark-H** [comment]
Can you check the contents of the install log in core/cache/logs? Also the config file?

**Comment by designbywilliam** [comment]
Ill do a reinstall on DO after the weekend and ill see if it happens again and then ill check the logs too.

**Comment by digitalpenguin** [comment]
Install log just shows:

[2015-01-23 10:01:35] (ERROR in xPDOConnection::connect @ /var/www/testgitify/core/xpdo/xpdo.class.php : 3043) SQLSTATE[42000] [1049] Unknown database 'testgitify'
[2015-01-23 10:01:35] (ERROR in xPDOConnection::connect @ /var/www/testgitify/core/xpdo/xpdo.class.php : 3043) SQLSTATE[42000] [1049] Unknown database 'testgitify'

**Comment by Mark-H** [comment]
Hi @digitalpenguin - that install log sounds like your database user can't create database tables. Try creating the database first and running install:modx after that.

**Comment by digitalpenguin** [comment]
Cheers Mark, the database was definitely created by gitify though. Root user. 
I'll try manually creating the database first and see if it makes a difference then report back.

**Comment by digitalpenguin** [comment]
Same thing still happening even with database already created. Curiously, this time there is no /core/cache/logs/ directory.

**Comment by Mark-H** [comment]
Closing as I can't reproduce.
