### ISSUE TITLE
Command Syntax - packages

### ISSUE THREAD

**Issue by Alroniks** [modmore/Gitify#56]
Hi colleagues.

Now gitify can install package by name and all packages from config. But if we want can full control on packages in MODX through API, we need more commands. But now command started from word `install:packages`. It's not right I think. In npm and composer exists at minimum 3 commands: install, update and remove (uninstall). If we keep old syntax, we needed write `gitify install:package Ace --update` or `gitify install:package Ace --remove`. WTF? Install and --remove? :) I guess you are laughing too. 

I propose to fix command syntax for package control.
```
gitify
    package
        install # installing of package
        remove # removing of package
        update # updating of package
        sync # sync all packages by config. Install not installed, and remove removed if needed.
```
If package not specified - install and remove and update all packages.
Examples:
`gitify package install Ace`
`gitify package update Ace`
`gitify package remove Lingua`
`gitify package sync`

I am ready to start with PR, but I need your's mentions.

**Comment by Mark-H** [comment]
Yeah, I think changing `install:package` to `package:install` to make room for `package:update` and similar makes sense. I like using the colon in between so Symfony recognises it as a namespace of sorts for the help.

`install:modx` should also become `modx:install` then ;)

If there's a way to implement a BC fix (some kind of command alias) that would be great, otherwise it's a matter of documenting the change.

**Comment by Mark-H** [comment]
This was renamed in ce9c5962907a874ffb38edebeb2c8917e67f928e
